# Default values for ibm-ace-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cp4d_namespace: cp4d-instance
cp4d_instance_name: ibmcpd-cr

license_accept: true
license: Enterprise
storage_vendor: portworx