apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
  name: cpd-operators
  namespace: {{ .Values.cp4d_namespace }}         # (Default) Replace with the Cloud Pak for Data platform operator project name 
spec:
  csvInjector:                    
    enable: true
  namespaceMembers:
  - {{ .Values.cp4d_namespace }}                 # (Default) Replace with the Cloud Pak for Data platform operator project name
